def computer_words_english(): #Have a list with english nouns
    words =["time", "year", "people", "way", "day", "man", "thing", "woman", "life", "child", "world", "school", "state", "family", "student", "group", "country", "problem", "hand", "part", "place", "case", "week", "company", "system", "program", "question", "work", "government", "number", "night", "point", "home", "water", "roof", "mother", "area", "money", "story", "fact", "month", "lot", "right", "study", "book", "eye", "job", "word", "business", "issue", "side", "kind", "head", "house", "service", "friend", "father", "power", "hour", "game", "line", "end", "member", "law", "car", "city", "community", "name", "president", "team", "minute", "idea", "kid", "body", "information", "back", "parent", "face", "others", "level", "office", "door", "health", "person", "art", "war", "history", "party", "result", "change", "morning", "reason", "research", "girl", "guy", "moment", "air", "teacher", "force", "education"]
    return words

def computer_words_swedish(): #Have a list with swedish nouns
    words =['adress', 'advokat', 'affär', 'afton', 'apelsin', 'apparat', 'arbetsplats', 'arm', 'ask', 'askkopp', 'avdelning', 'axel', 'bagare', 'bakelse', 'balkong', 'bana', 'banan', 'bandspelare', 'bar', 'barnskötare', 
    'berättelse', 'bil', 'bild', 'biljett', 'blomma', 'blus', 'bok', 'boll', 'brandman', 'brevlåda', 'broder', 'bulle', 'buss', 'bussförare', 'butik', 'båt', 'bänk', 'chaufför', 'check', 'cigarett', 'citron', 'cykel', 'dag', 'dator', 'deltagare', 'diskbänk', 'diskmaskin', 'dotter', 'dräkt', 'duk', 'dush', 'dörr', 'elefant', 'elev', 'expedit', 'fabrik', 'familj', 'pappa', 'farbror', 'fax', 'film', 'fisk', 'fjärrkontroll', 'flaska', 'flicka', 'fluga', 'flygplats', 'fläkt', 'fot', 'fotboll', 'fotbollspelare', 'frisör', 'fru', 'frukost', 'frukt', 'frys', 'fysiker', 'fågel', 'fåtölj', 'färg', 'förman', 'förmiddag', 'förälder', 'gaffel', 'gardin', 'gata', 'glass', 'gran', 'grönsak', 'gurka', 'hall', 'hamn', 'hand', 'handduk', 'handske', 'hatt', 'hund', 'hustru', 'hylla', 'hållplats', 'händelse', 'häst', 'högtalare', 'idé', 'idiot', 'italienare', 'jacka', 'jordgubbe', 'journalist', 'jumper', 'järnvägsstation', 'kaka', 'kalender', 'kam', 'kamera', 'kamrat', 'karta', 'kassa', 'kasse', 'kassörska', 'katt', 'kille', 'kiosk', 'kjol', 'klocka', 'klädhängare', 'klänning', 'kniv', 'ko', 'kokbok', 'kompis', 'kopp', 'kostym', 'kran', 'krona', 'kropp', 'kudde', 'kund', 'kurs', 'kusin', 'kvinna', 'kyl', 'källare', 'lampa', 'lapp', 'lucka', 'lunch', 'låda', 
    'lägenhet', 'läkare', 'lärare', 'läxa', 'lök', 'madrass', 'maka', 'make', 'mamma', 'man', 'mangel', 'maskin', 'matta', 'medicin', 'mekaniker', 'mening', 'minut', 'moder', 'mor', 'morbror', 'morgon', 'morot', 'moster', 'mugg', 'mun', 'musiker', 'målare', 'månad', 'människa', 'möbel', 'mössa', 'nagel', 'natt', 'nyckel', 'ordningsman', "ort", "pappa", "paprika", "park", "peng", "penna", "pennvässare", "person", "personuppgift", "pipa", "plånbok", "pojke", "polis", "post", "påse", "påve", "pärm", "rad", "radio", "rand", "restaurang", "ring", "rock", "ros", "rot", "räkning", "sak", "sand", "servitris", "servitör", "sida", "signal", "sjöman", "sked", "skillnad", "sko", "skog", "skola", "skomakare", "skådespelare", "släkting", "soffa", "sol", "somalier", "sommar", "son", "soppa", "sotare", "spegel", "spis", "stad", "stam", "station", "stereo", "stol", "strand", "strumpa", "svärson", "syster", "säng", "tabell", "tand", "tandborste", "tandkräm", "tanke", "tavla"]
    return words

#CREDITS
#Ella Rejström